env: gw2d

env_args:
  map_rows: 15
  map_cols: 15
  n_agents: 2
  episode_limit: 100
  randomized: True

test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 2000
learner_log_interval: 2000
t_max: 2000000
